# Generated by Django 4.1.5 on 2023-02-12 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arwaz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Address',
            field=models.CharField(default='', max_length=260),
            preserve_default=False,
        ),
    ]
