# Generated by Django 4.1.5 on 2023-02-12 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arwaz', '0002_student_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='state',
            field=models.CharField(default='pilibhit', max_length=160, null=True),
        ),
    ]
