# Generated by Django 4.1.5 on 2023-03-04 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arwaz', '0005_employes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employes',
        ),
    ]
